### ISSUE TITLE
params[key].includes is not a function

### ISSUE THREAD

**Issue by bharathvaj1995** [Paytm-Payments/Paytm_App_Checksum_Kit_NodeJs#6]
Why is this happening to frequently?

**Comment by ravishan110** [comment]
Anyone who has solved this error? I am getting the same issue.

**Comment by hkchakladar** [comment]
Same error here. No support from @Paytm-Payments-Admin ?

**Comment by neelgeek** [comment]
This Issue occurs when any of the Attributes in the Object Passed to the **genchecksum** Function is not String. In my case,I was passing the `TXN_AMOUNT` variable as Number. Fixed it by converting to String before passing to the function.

**Comment by VAIBHAVCES** [comment]
> This Issue occurs when any of the Attributes in the Object Passed to the **genchecksum** Function is not String. In my case,I was passing the `TXN_AMOUNT` variable as Number. Fixed it by converting to String before passing to the function.

Hi very nice bro,  this solution worked out for me I was also trying to hardcode the amount in a  number format putting just the amount in quotes worked out for me
